[package]
name = "zkvm"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
risc0-zkvm = { version = "2.0.1" }

[build-dependencies]
risc0-build = { version = "2.0.1" }

[package.metadata.risc0]
methods = ["./program"]
