services:
  db:
    image: postgres
    restart: always
    container_name: zk_arcade_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zk_arcade_dev
    ports:
      - "5433:5432"
